### ISSUE TITLE
question：module 'tensorflow.contrib.layers' has no attribute 'conv3d'

### ISSUE THREAD

**Issue by mingmingfu** [liu-nlper/NER-LSTM-CRF#18]
conv3d在1.2版本中是在tf.nn.conv3d下，但是输入参数和您的不一致？

**Comment by liu-nlper** [comment]
我是在tf v1.4下测试的，v1.2的conv3d参数顺序之类的可能不太一样

**Comment by mingmingfu** [comment]
[https://www.tensorflow.org/api_docs/python/tf/nn/conv3d](url)

**Comment by mingmingfu** [comment]
1.4文档中的参数和您的也不一样，和1.2的一致

**Comment by mingmingfu** [comment]
1.4下的参数和您代码的也不一致呢

**Comment by liu-nlper** [comment]
你是不是看的tf.nn.conv3d呢？这个和tensorflow.contrib.layers.conv3d里参数确实不一样

**Comment by mingmingfu** [comment]
我并没有在tf.contrib.layers找到这个函数呢。有一个conv3d_transpose，是不是改名了？

**Comment by liu-nlper** [comment]
@mingmingfu conv2d，别名也可以用conv3d，你看下下面的
https://www.tensorflow.org/api_docs/python/tf/contrib/layers/conv2d

**Comment by mingmingfu** [comment]
哦哦，好的。谢谢～我看下
