### ISSUE TITLE
model.py 中 第九行  tqdm 是什么鬼，没找到这个呀

### ISSUE THREAD

**Issue by LawLietzh** [liu-nlper/NER-LSTM-CRF#20]
model.py 中 第九行  tqdm 是什么鬼，没找到这个呀

**Comment by liu-nlper** [comment]
pip install tqdm

**Comment by LawLietzh** [comment]
model.py 这个文件中有 from tqdm import tqdm，请问 tqdm 这个文件在哪

在 2018-03-19 11:09:49，"ljx" <notifications@github.com> 写道：


Closed #20.

**Comment by liu-nlper** [comment]
@LawLietzh pip install tqdm

**Comment by LawLietzh** [comment]
我靠 受教了，python 居然还有这个模块

At 2018-03-19 11:17:02, "ljx" <notifications@github.com> wrote:


@LawLietzh pip install tqdm
