### ISSUE TITLE
你好 有个问题

### ISSUE THREAD

**Issue by LuckyPickleZZ** [liu-nlper/NER-LSTM-CRF#22]
我跑preprocess和train的时候，都出现了list indices must be integers or slices, not str
请问这个怎么解决

**Comment by LuckyPickleZZ** [comment]
Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/NER-LSTM-CRF-master/train.py", line 97, in <module>
    main()
  File "C:/Users/lenovo/Desktop/NER-LSTM-CRF-master/train.py", line 27, in main
    config['model_params']['embed_params']['feature_name']['shape']
TypeError: list indices must be integers or slices, not str

**Comment by liu-nlper** [comment]
```
masked_cur_partition = cur_partition.masked_select(mask_idx)
if masked_cur_partition.dim() != 0:
    mask_idx = mask_idx.contiguous().view(batch_size, tag_size, 1)
    partition.masked_scatter_(mask_idx, masked_cur_partition)
```

**Comment by whuzzh** [comment]
你好 请问测试的时候测试文件格式是怎样的？
测试文件需要自己预先构造好分词和词性标注，然后结果会生成实体识别结果？

**Comment by LuckyPickleZZ** [comment]
是
