### ISSUE TITLE
utils部分代码

### ISSUE THREAD

**Issue by bunnyfighting** [liu-nlper/NER-LSTM-CRF#5]
您好：
        非常感谢您分享您的代码，能够自动生成配置文件感觉很好。
        不过貌似缺少utils中， create_dictionary、 load_embed_from_txt 的代码，请问可以上传这部分代码吗？
         谢谢啦~

**Comment by liu-nlper** [comment]
您好，这两个函数在utils.py中都有的，分别在62、184行。

**Comment by bunnyfighting** [comment]
不好意思是我大意了，自己加了utils包导致运行出错。
      谢谢~
