### ISSUE TITLE
InvalidArgumentError (see above for traceback): indices[21,1] = 2058 is not in [0, 2038)

### ISSUE THREAD

**Issue by j-pl** [liu-nlper/NER-LSTM-CRF#7]
你好〜
我尝试训练...
但有报错....
附件为训练样本: 
[sample_train.txt](https://github.com/liu-nlper/NER-LSTM-CRF/files/1283501/sample_train.txt)

还有char_embed.pkl和embedding.txt是如何训练？

謝謝~~!

**Comment by liu-nlper** [comment]
你好，
1. 我用了你的训练样本可以正常训练的。在运行了preprocessing.py之后生成了配置文件config.yml，你修改过配置文件中的哪些内容？
2. embedding.txt是提供的预训练的词向量，可以用[gensim](https://radimrehurek.com/gensim/)训练，char_embed.pkl是预处理时从embedding.txt抽出的需要的词向量，并保存成二进制文件，加快加载

**Comment by j-pl** [comment]
1. 找到原因了，因为尝试无预训练embedding的训练，将model_params.embed_params.f1.path_pre_train设成null，设回后正常训练。
2. 用gensim训练embedding.txt，我做了一个训练程序，试了可以的，请教有哪些方面可以改进优化？
config.yml加了path_train_embedding_words：

> 
> data_params:
>   path_result: ./data/sample_test_result.txt
>   path_test: ./data/sample_test.txt
>   path_train: ./data/sample_train.txt
>   path_train_embedding_words: ./data/sample_train_words.txt
> 

[sample_train_words.txt](https://github.com/liu-nlper/NER-LSTM-CRF/files/1285138/sample_train_words.txt)
[test_gensim.py](https://github.com/liu-nlper/NER-LSTM-CRF/files/1285093/test_gensim.txt)

謝謝~~

**Comment by liu-nlper** [comment]
你好，
1. 如果要无预训练embedding训练，要将path_pre_train和path都设为null再进行预处理；
2. 要预训练字向量的话，sample_train_words.txt文件中需要将每个句子放在一行，字与字之间用空格隔开，并不是每个字单独放在一行；
3. word embedding训练的话有几个参数可以调整的，具体见官网api~

**Comment by j-pl** [comment]
看到你的Utils，明白很多~~ 你写的很容易懂～
还有一个就问题，如果有很多新词在predict出现，该如何分别unknown label？
我参考了 [`deepnlp ner reader`](https://github.com/rockingdingo/deepnlp/blob/9a5717e1c7dca3247af1c9e5ca221f374cf95220/deepnlp/ner/reader.py#L91)

是否应该在preprocessing.py 预设加上unknown label?
line: 52 - 62 [preprocessing.py](https://github.com/liu-nlper/NER-LSTM-CRF/files/1294627/preprocessing.txt)
