### ISSUE TITLE
should dropout be set to zero when inference?

### ISSUE THREAD

**Issue by Alex-X-W** [liu-nlper/NER-LSTM-CRF#9]
Hi liu-nlper,

Nice work and an easy to follow README!

But I noticed in your testing phase, you still construct the model such that its dropout equals what's in the config. Was is a design out of some special consideration? Cuz usually when inference we use the complete model without dropout.

Thanks!
Xuan

**Comment by liu-nlper** [comment]
Hi Xuan, I have set dropout to zero in the 305th and 339th in the 'model.py'.
